[tool.poetry]
name = "verilog-parser"
version = "0.1.0"
description = ""
authors = ["Jose Renau <renau@ucsc.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
tree-sitter = "=0.20.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
